### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.String com.paytabs.paytabs_sdk.http.PrepareTransactionResponse.getResponseCode()' on a null object reference at com.paytabs.paytabs_sdk.payment.ui.activities.PayTabActivity.onAPICallSuccess(PayTabActivity.java:327)

### ISSUE THREAD

**Issue by DilipRipenApps** [paytabscom/paytabs-android-library-sample#17]
Attempt to invoke virtual method 'java.lang.String com.paytabs.paytabs_sdk.http.PrepareTransactionResponse.getResponseCode()' on a null object reference
        at com.paytabs.paytabs_sdk.payment.ui.activities.PayTabActivity.onAPICallSuccess(PayTabActivity.java:327)
        at com.paytabs.paytabs_sdk.http.HttpRequests$3.onResponse(HttpRequests.java:81)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
        at retrofit2.-$$Lambda$DefaultCallAdapterFactory$ExecutorCallbackCall$1$hVGjmafRi6VitDIrPNdoFizVAdk.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by mohamedkhairy953** [comment]
please try the latest version 5.0.7
