### ISSUE TITLE
crash in android kotlin sample

### ISSUE THREAD

**Issue by aboali712** [paytabscom/paytabs-android-library-sample#18]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.paytabs.sample.kotlin, PID: 3156
    java.lang.NullPointerException: throw with null exception
        at com.paytabs.paytabs_sdk.http.e.a(Unknown Source:1)
        at com.paytabs.paytabs_sdk.payment.ui.activities.PayTabActivity.onAPICallSuccess(Unknown Source:267)
        at com.paytabs.paytabs_sdk.http.c$c.onResponse(Unknown Source:12)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7948)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

**Comment by mohamedkhairy953** [comment]
https://github.com/paytabscom/paytabs-android-library-sample/blob/master/sdk/paytabs_sdk-v5.0.7.aar
please try the this version and let me know
