### ISSUE TITLE
Too Large Exception for data parcel

### ISSUE THREAD

**Issue by mohsinbutt2020** [paytabscom/paytabs-android-library-sample#28]
**### When i use merchen logo then i get this issue for android version 8 and less version or on low memory devices**

com.payment.paymentsdk.PaymentSdkActivity, giving up
    android.os.TransactionTooLargeException: data parcel size 751684 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:763)
        at android.app.IApplicationThread$Stub$Proxy.scheduleLaunchActivity(IApplicationThread.java:1282)
        at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1734)
        at com.android.server.am.ActivityStackSupervisor.attachApplicationLocked(ActivityStackSupervisor.java:1152)
        at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:9184)
        at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:9254)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:291)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3863)
        at android.os.Binder.execTransact(Binder.java:682)

**Comment by mohamedkhairy953** [comment]
This exception indicates that you logo is too large to be passed through bundle, so that we have overloaded this method to accept url instead of the drawable.

You can pass the logo url or its relative path and it will work correctly.

**Comment by mohsinbutt2020** [comment]
I checked all the possibilities with drawable image, in-fact i passed 4kb of image from drawable but that did not work.. It only work with almost all new devices from android 9 onward.

**Comment by mohamedkhairy953** [comment]
Yes, as it depends on different factors not just the logo size, so we
recommend passing url as it is more stable.

**Comment by mohsinbutt2020** [comment]
Ok Thanks...
